apiVersion: v1
kind: ConfigMap
metadata:
  name: authos-api-config
  namespace: authos
data:
  REDIS_HOST: "redis-master.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  DB_HOST: "authos-pg-cluster-rw.pg-cluster.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "authos"
  KEYSTORE_PATH: "/etc/keystore/keystore.p12"
  FRONTEND_COOKIE_DOMAIN: ""
  API_COOKIE_DOMAIN: ""
  FRONTEND_HOST: "http://localhost:3000"
  API_HOST: "http://localhost:8080"
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
