apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authos-api-ingress
  namespace: authos
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public-nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authos-api
                port:
                  number: 80
