apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authos

resources:
  - ../../base
  -
replicas:
  - count: 3
    name: authos-ui

images:
  - name: stevetosak/authos-ui
    newTag: latest
