apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authos

resources:
  - ../../base

images:
  - name: stevetosak/authos-api
    newTag: latest
replicas:
  - count: 3
    name: authos-api