apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: private-apps
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.100.0.0/24
spec:
  ingressClassName: private-nginx
  rules:
    - host: whoami.internal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
