apiVersion: v1
kind: Service
metadata:
  name: private-ingress-service
  namespace: ingress-private
spec:
  type: NodePort
  selector:
    app: ingress-nginx
  ports:
    - port: 80
      nodePort: 30080
      name: http
      targetPort: http
    - port: 443
      nodePort: 30443
      name: https
      targetPort: https
