apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authos-lb-ingress
  namespace: authos
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: public-nginx
  tls:
    - hosts:
        - authos.tosak.net
        - api.authos.tosak.net
      secretName: authos-tls
  rules:
    - host: authos.tosak.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authos-ui
                port:
                  number: 80
    - host: api.authos.tosak.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authos-api
                port:
                  number: 80
