apiVersion: apps/v1
kind: Deployment
metadata:
  name: authos-ui
  labels:
    app: authos-ui
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: authos-ui
  template:
    metadata:
      name: authos-ui
      labels:
        app: authos-ui
    spec:
      containers:
        - name: authos-ui
          image: stevetosak/authos-ui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: authos-ui-config
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      